<?php

const PARTIDOS = "PARTIDOS";
const PAR_ID = "PAR_ID";
const PAR_FECHA = "PAR_FECHA";
const PAR_GOL_LOCAL = "PAR_GOL_LOCAL";
const PAR_GOL_VISITANTE = "PAR_GOL_VISITANTE";
const PAR_LOCAL = "PAR_LOCAL";
const PAR_VISITANTE = "PAR_VISITANTE";